# Generated by Django 2.0.2 on 2018-02-19 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(max_length=13)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='upvotes',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='upvotes',
            name='user_upvotes',
        ),
        migrations.DeleteModel(
            name='Upvotes',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
